name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove esta linha se você deseja publicar seu pacote

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  intl: ^0.18.0
  pdf: ^3.6.0
  path_provider: ^2.0.2
  printing: ^5.10.0
  open_file: ^3.2.1
  permission_handler: ^10.2.0
  flutter_downloader: ^1.7.3
  syncfusion_flutter_pdfviewer: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_azul.jpg
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/open-sans.ttf